In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [106]:
df = pd.read_csv("Elite.csv", encoding="latin-1")

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               5000 non-null   str
 1   Model               5000 non-null   str
 2   Year                5000 non-null   int64
 3   Country             5000 non-null   str
 4   Condition           5000 non-null   str
 5   Engine_Size         5000 non-null   float64
 6   Horsepower          5000 non-null   int64
 7   Torque              5000 non-null   int64
 8   Weight              5000 non-null   int64
 9   Top_Speed           5000 non-null   int64
 10  Acceleration_0_100  5000 non-null   float64
 11  Fuel_Type           5000 non-null   str
 12  Drivetrain          5000 non-null   str
 13  Transmission        5000 non-null   str
 14  Fuel_Efficiency     5000 non-null   float64
 15  CO2_Emissions       5000 non-null   int64
 16  Price               5000 non-null   int64
 17  Mileage             5000 non-null   int64
 18  Popularity          5000 non-null   str
 19  Safety_Rating       5000 non-null   int64
 20  Number_of_Owners    5000 non-null   int64
 21  Market_Demand       5000 non-null   str
 22  Insurance_Cost      5000 non-null   int64
 23  Production_Units    5000 non-null   int64
 24  Log_Price           5000 non-null   float64
 25  Log_Mileage         5000 non-null   float64
 26  Modification        1977 non-null   str
dtypes: float64(5), int64(12), str(10)
memory usage: 1.0 MB

In [20]:
df.head()

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
0,Nissan,720S,2006,Asia,used,3.7,420,705,1785,238,...,96664,Low,2,4,Medium,13410,5000,11.309352,11.479007,V-Spec
1,McLaren,911 Turbo S,2009,Europe,new,5.3,1104,766,992,386,...,159630,High,2,2,Medium,10795,1000,12.639334,11.980620,NaN
2,Chevrolet,M4 Competition,2009,USA,new,5.5,153,1573,2022,397,...,111496,High,1,2,Low,1716,20000,12.948902,11.621753,NaN
3,Bugatti,Chiron,1982,Asia,used,5.4,544,1009,1091,151,...,217228,High,2,4,Medium,11618,20000,11.725542,12.288707,NaN
4,Nissan,Chiron,2022,Europe,new,2.4,980,693,1232,385,...,150318,Low,3,2,Medium,11324,100000,11.229289,11.920515,NaN

In [21]:
df.tail()

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
4995,Nissan,GT-R,2011,USA,used,3.9,1392,514,1049,284,...,80352,Low,1,3,Medium,10428,5000,12.423452,11.294185,NaN
4996,McLaren,M4 Competition,2021,USA,new,6.9,256,662,2131,223,...,164451,High,1,3,Low,1134,50,12.781219,12.010374,V-Spec
4997,Bugatti,911 Turbo S,1983,Europe,new,6.3,212,123,2272,289,...,30314,Low,4,1,High,7107,100000,11.912057,10.319398,NaN
4998,Porsche,M4 Competition,2023,Asia,new,7.3,1373,228,1161,204,...,13144,Low,4,2,High,11219,5000,12.473306,9.483797,Turbo
4999,McLaren,Chiron,2018,Europe,new,7.7,1075,1037,1312,381,...,57970,High,2,3,High,1802,20000,11.267536,10.967698,Sport

In [28]:
df.columns

Index(['Brand', 'Model', 'Year', 'Country', 'Condition', 'Engine_Size',
       'Horsepower', 'Torque', 'Weight', 'Top_Speed', 'Acceleration_0_100',
       'Fuel_Type', 'Drivetrain', 'Transmission', 'Fuel_Efficiency',
       'CO2_Emissions', 'Price', 'Mileage', 'Popularity', 'Safety_Rating',
       'Number_of_Owners', 'Market_Demand', 'Insurance_Cost',
       'Production_Units', 'Log_Price', 'Log_Mileage', 'Modification'],
      dtype='str')

In [29]:
df.shape

(5000, 27)

In [30]:
df.index

RangeIndex(start=0, stop=5000, step=1)

In [31]:
df.dtypes

Brand                     str
Model                     str
Year                    int64
Country                   str
Condition                 str
Engine_Size           float64
Horsepower              int64
Torque                  int64
Weight                  int64
Top_Speed               int64
Acceleration_0_100    float64
Fuel_Type                 str
Drivetrain                str
Transmission              str
Fuel_Efficiency       float64
CO2_Emissions           int64
Price                   int64
Mileage                 int64
Popularity                str
Safety_Rating           int64
Number_of_Owners        int64
Market_Demand             str
Insurance_Cost          int64
Production_Units        int64
Log_Price             float64
Log_Mileage           float64
Modification              str
dtype: object

In [33]:
df.describe()

,Year,Engine_Size,Horsepower,Torque,Weight,Top_Speed,Acceleration_0_100,Fuel_Efficiency,CO2_Emissions,Price,Mileage,Safety_Rating,Number_of_Owners,Insurance_Cost,Production_Units,Log_Price,Log_Mileage
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2001.904800,4.828700,822.891600,938.800600,1689.724200,274.857000,4.517280,10.038340,272.695200,262067.329400,126487.020800,2.502200,2.479200,7749.857800,26496.010000,12.266985,11.449482
std,12.873697,1.858353,401.362549,472.954278,465.786421,72.062214,1.448473,2.881613,100.154245,137678.803906,72773.504601,1.119038,1.114368,4177.751738,36767.027776,0.741124,0.973881
min,1980.000000,1.600000,130.000000,120.000000,900.000000,150.000000,2.000000,5.000000,100.000000,20014.000000,47.000000,1.000000,1.000000,501.000000,50.000000,9.904237,3.871201
25%,1991.000000,3.200000,472.000000,522.000000,1286.000000,214.000000,3.300000,7.600000,186.000000,143710.750000,63809.750000,1.000000,1.000000,4106.750000,1000.000000,11.875565,11.063677
50%,2002.000000,4.800000,815.500000,948.000000,1684.000000,275.000000,4.500000,10.000000,273.000000,265213.500000,126762.500000,3.000000,2.000000,7697.500000,5000.000000,12.488294,11.750078
75%,2013.000000,6.500000,1176.000000,1345.000000,2101.000000,337.000000,5.800000,12.600000,357.000000,380923.500000,190287.500000,3.000000,3.000000,11351.750000,20000.000000,12.850356,12.156297
max,2024.000000,8.000000,1521.000000,1758.000000,2499.000000,399.000000,7.000000,15.000000,449.000000,499991.000000,249956.000000,4.000000,4.000000,14998.000000,100000.000000,13.122347,12.429044

In [34]:
df.isnull()

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [35]:
df.isnull().sum()

Brand                    0
Model                    0
Year                     0
Country                  0
Condition                0
Engine_Size              0
Horsepower               0
Torque                   0
Weight                   0
Top_Speed                0
Acceleration_0_100       0
Fuel_Type                0
Drivetrain               0
Transmission             0
Fuel_Efficiency          0
CO2_Emissions            0
Price                    0
Mileage                  0
Popularity               0
Safety_Rating            0
Number_of_Owners         0
Market_Demand            0
Insurance_Cost           0
Production_Units         0
Log_Price                0
Log_Mileage              0
Modification          3023
dtype: int64

In [36]:
print(df.columns)

Index(['Brand', 'Model', 'Year', 'Country', 'Condition', 'Engine_Size',
       'Horsepower', 'Torque', 'Weight', 'Top_Speed', 'Acceleration_0_100',
       'Fuel_Type', 'Drivetrain', 'Transmission', 'Fuel_Efficiency',
       'CO2_Emissions', 'Price', 'Mileage', 'Popularity', 'Safety_Rating',
       'Number_of_Owners', 'Market_Demand', 'Insurance_Cost',
       'Production_Units', 'Log_Price', 'Log_Mileage', 'Modification'],
      dtype='str')

In [37]:
df.columns

Index(['Brand', 'Model', 'Year', 'Country', 'Condition', 'Engine_Size',
       'Horsepower', 'Torque', 'Weight', 'Top_Speed', 'Acceleration_0_100',
       'Fuel_Type', 'Drivetrain', 'Transmission', 'Fuel_Efficiency',
       'CO2_Emissions', 'Price', 'Mileage', 'Popularity', 'Safety_Rating',
       'Number_of_Owners', 'Market_Demand', 'Insurance_Cost',
       'Production_Units', 'Log_Price', 'Log_Mileage', 'Modification'],
      dtype='str')

In [41]:
df[['Brand','Price']].head(10).head(10)

       Brand   Price
0     Nissan   81580
1    McLaren  308455
2  Chevrolet  420374
3    Bugatti  123690
4     Nissan   75303
5        BMW  478142
6    Porsche  398429
7     Nissan  133803
8  Chevrolet  245162
9    Bugatti  451504

In [43]:
df[['Brand','Model','Year','Price']].sort_values(by='Year').head(10)

             Brand        Model  Year   Price
4955  Aston Martin       Chiron  1980  218810
1698           BMW  911 Turbo S  1980  174094
3896          Ford  911 Turbo S  1980  286395
1603       Ferrari         720S  1980  468932
1590       Bugatti         GT-R  1980  140444
3859           BMW  911 Turbo S  1980  123392
1582  Aston Martin      Huracan  1980  129929
3227  Aston Martin      488 GTB  1980  219267
337           Ford      Huracan  1980  483118
2623       Bugatti      Huracan  1980   89177

In [49]:
mean_P=df['Price'].mean()
print(mean_P)

262067.3294

In [60]:
df['Year'].median()

np.float64(2002.0)

In [58]:
df['Brand'].mode()[0]

'Ferrari'

In [64]:
df.groupby("Brand")["Price"].mean()

Brand
Aston Martin    256236.752437
BMW             276471.391129
Bugatti         265088.418146
Chevrolet       267751.664729
Ferrari         256136.947467
Ford            252898.777778
Lamborghini     259313.717021
McLaren         267438.755144
Nissan          259352.085417
Porsche         260090.085770
Name: Price, dtype: float64

In [76]:
df.head(7)

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
0,Nissan,720S,2006,Asia,used,3.7,420,705,1785,238,...,96664,Low,2,4,Medium,13410,5000,11.309352,11.479007,V-Spec
1,McLaren,911 Turbo S,2009,Europe,new,5.3,1104,766,992,386,...,159630,High,2,2,Medium,10795,1000,12.639334,11.980620,NaN
2,Chevrolet,M4 Competition,2009,USA,new,5.5,153,1573,2022,397,...,111496,High,1,2,Low,1716,20000,12.948902,11.621753,NaN
3,Bugatti,Chiron,1982,Asia,used,5.4,544,1009,1091,151,...,217228,High,2,4,Medium,11618,20000,11.725542,12.288707,NaN
4,Nissan,Chiron,2022,Europe,new,2.4,980,693,1232,385,...,150318,Low,3,2,Medium,11324,100000,11.229289,11.920515,NaN
5,BMW,GT-R,1986,Europe,new,5.4,1091,632,2135,341,...,228779,High,2,3,Medium,5274,200,13.077665,12.340516,NaN
6,Porsche,720S,1988,Asia,new,4.2,810,1222,2130,245,...,222953,Medium,4,3,Medium,5645,5000,12.895287,12.314721,Nismo

In [77]:
df.shape

(5000, 27)

In [78]:
df.info

<bound method DataFrame.info of           Brand           Model  Year Country Condition  Engine_Size  \
0        Nissan            720S  2006    Asia      used          3.7
1       McLaren     911 Turbo S  2009  Europe       new          5.3
2     Chevrolet  M4 Competition  2009     USA       new          5.5
3       Bugatti          Chiron  1982    Asia      used          5.4
4        Nissan          Chiron  2022  Europe       new          2.4
...         ...             ...   ...     ...       ...          ...
4995     Nissan            GT-R  2011     USA      used          3.9
4996    McLaren  M4 Competition  2021     USA       new          6.9
4997    Bugatti     911 Turbo S  1983  Europe       new          6.3
4998    Porsche  M4 Competition  2023    Asia       new          7.3
4999    McLaren          Chiron  2018  Europe       new          7.7

      Horsepower  Torque  Weight  Top_Speed  ...  Mileage Popularity  \
0            420     705    1785        238  ...    96664        Low
1           1104     766     992        386  ...   159630       High
2            153    1573    2022        397  ...   111496       High
3            544    1009    1091        151  ...   217228       High
4            980     693    1232        385  ...   150318        Low
...          ...     ...     ...        ...  ...      ...        ...
4995        1392     514    1049        284  ...    80352        Low
4996         256     662    2131        223  ...   164451       High
4997         212     123    2272        289  ...    30314        Low
4998        1373     228    1161        204  ...    13144        Low
4999        1075    1037    1312        381  ...    57970       High

     Safety_Rating Number_of_Owners  Market_Demand  Insurance_Cost  \
0                2                4         Medium           13410
1                2                2         Medium           10795
2                1                2            Low            1716
3                2                4         Medium           11618
4                3                2         Medium           11324
...            ...              ...            ...             ...
4995             1                3         Medium           10428
4996             1                3            Low            1134
4997             4                1           High            7107
4998             4                2           High           11219
4999             2                3           High            1802

      Production_Units  Log_Price Log_Mileage  Modification
0                 5000  11.309352   11.479007        V-Spec
1                 1000  12.639334   11.980620           NaN
2                20000  12.948902   11.621753           NaN
3                20000  11.725542   12.288707           NaN
4               100000  11.229289   11.920515           NaN
...                ...        ...         ...           ...
4995              5000  12.423452   11.294185           NaN
4996                50  12.781219   12.010374        V-Spec
4997            100000  11.912057   10.319398           NaN
4998              5000  12.473306    9.483797         Turbo
4999             20000  11.267536   10.967698         Sport

[5000 rows x 27 columns]>

In [79]:
df.columns

Index(['Brand', 'Model', 'Year', 'Country', 'Condition', 'Engine_Size',
       'Horsepower', 'Torque', 'Weight', 'Top_Speed', 'Acceleration_0_100',
       'Fuel_Type', 'Drivetrain', 'Transmission', 'Fuel_Efficiency',
       'CO2_Emissions', 'Price', 'Mileage', 'Popularity', 'Safety_Rating',
       'Number_of_Owners', 'Market_Demand', 'Insurance_Cost',
       'Production_Units', 'Log_Price', 'Log_Mileage', 'Modification'],
      dtype='str')

In [80]:
df.tail

<bound method NDFrame.tail of           Brand           Model  Year Country Condition  Engine_Size  \
0        Nissan            720S  2006    Asia      used          3.7
1       McLaren     911 Turbo S  2009  Europe       new          5.3
2     Chevrolet  M4 Competition  2009     USA       new          5.5
3       Bugatti          Chiron  1982    Asia      used          5.4
4        Nissan          Chiron  2022  Europe       new          2.4
...         ...             ...   ...     ...       ...          ...
4995     Nissan            GT-R  2011     USA      used          3.9
4996    McLaren  M4 Competition  2021     USA       new          6.9
4997    Bugatti     911 Turbo S  1983  Europe       new          6.3
4998    Porsche  M4 Competition  2023    Asia       new          7.3
4999    McLaren          Chiron  2018  Europe       new          7.7

      Horsepower  Torque  Weight  Top_Speed  ...  Mileage Popularity  \
0            420     705    1785        238  ...    96664        Low
1           1104     766     992        386  ...   159630       High
2            153    1573    2022        397  ...   111496       High
3            544    1009    1091        151  ...   217228       High
4            980     693    1232        385  ...   150318        Low
...          ...     ...     ...        ...  ...      ...        ...
4995        1392     514    1049        284  ...    80352        Low
4996         256     662    2131        223  ...   164451       High
4997         212     123    2272        289  ...    30314        Low
4998        1373     228    1161        204  ...    13144        Low
4999        1075    1037    1312        381  ...    57970       High

     Safety_Rating Number_of_Owners  Market_Demand  Insurance_Cost  \
0                2                4         Medium           13410
1                2                2         Medium           10795
2                1                2            Low            1716
3                2                4         Medium           11618
4                3                2         Medium           11324
...            ...              ...            ...             ...
4995             1                3         Medium           10428
4996             1                3            Low            1134
4997             4                1           High            7107
4998             4                2           High           11219
4999             2                3           High            1802

      Production_Units  Log_Price Log_Mileage  Modification
0                 5000  11.309352   11.479007        V-Spec
1                 1000  12.639334   11.980620           NaN
2                20000  12.948902   11.621753           NaN
3                20000  11.725542   12.288707           NaN
4               100000  11.229289   11.920515           NaN
...                ...        ...         ...           ...
4995              5000  12.423452   11.294185           NaN
4996                50  12.781219   12.010374        V-Spec
4997            100000  11.912057   10.319398           NaN
4998              5000  12.473306    9.483797         Turbo
4999             20000  11.267536   10.967698         Sport

[5000 rows x 27 columns]>

In [81]:
df.tail()

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
4995,Nissan,GT-R,2011,USA,used,3.9,1392,514,1049,284,...,80352,Low,1,3,Medium,10428,5000,12.423452,11.294185,NaN
4996,McLaren,M4 Competition,2021,USA,new,6.9,256,662,2131,223,...,164451,High,1,3,Low,1134,50,12.781219,12.010374,V-Spec
4997,Bugatti,911 Turbo S,1983,Europe,new,6.3,212,123,2272,289,...,30314,Low,4,1,High,7107,100000,11.912057,10.319398,NaN
4998,Porsche,M4 Competition,2023,Asia,new,7.3,1373,228,1161,204,...,13144,Low,4,2,High,11219,5000,12.473306,9.483797,Turbo
4999,McLaren,Chiron,2018,Europe,new,7.7,1075,1037,1312,381,...,57970,High,2,3,High,1802,20000,11.267536,10.967698,Sport

In [82]:
df.info

<bound method DataFrame.info of           Brand           Model  Year Country Condition  Engine_Size  \
0        Nissan            720S  2006    Asia      used          3.7
1       McLaren     911 Turbo S  2009  Europe       new          5.3
2     Chevrolet  M4 Competition  2009     USA       new          5.5
3       Bugatti          Chiron  1982    Asia      used          5.4
4        Nissan          Chiron  2022  Europe       new          2.4
...         ...             ...   ...     ...       ...          ...
4995     Nissan            GT-R  2011     USA      used          3.9
4996    McLaren  M4 Competition  2021     USA       new          6.9
4997    Bugatti     911 Turbo S  1983  Europe       new          6.3
4998    Porsche  M4 Competition  2023    Asia       new          7.3
4999    McLaren          Chiron  2018  Europe       new          7.7

      Horsepower  Torque  Weight  Top_Speed  ...  Mileage Popularity  \
0            420     705    1785        238  ...    96664        Low
1           1104     766     992        386  ...   159630       High
2            153    1573    2022        397  ...   111496       High
3            544    1009    1091        151  ...   217228       High
4            980     693    1232        385  ...   150318        Low
...          ...     ...     ...        ...  ...      ...        ...
4995        1392     514    1049        284  ...    80352        Low
4996         256     662    2131        223  ...   164451       High
4997         212     123    2272        289  ...    30314        Low
4998        1373     228    1161        204  ...    13144        Low
4999        1075    1037    1312        381  ...    57970       High

     Safety_Rating Number_of_Owners  Market_Demand  Insurance_Cost  \
0                2                4         Medium           13410
1                2                2         Medium           10795
2                1                2            Low            1716
3                2                4         Medium           11618
4                3                2         Medium           11324
...            ...              ...            ...             ...
4995             1                3         Medium           10428
4996             1                3            Low            1134
4997             4                1           High            7107
4998             4                2           High           11219
4999             2                3           High            1802

      Production_Units  Log_Price Log_Mileage  Modification
0                 5000  11.309352   11.479007        V-Spec
1                 1000  12.639334   11.980620           NaN
2                20000  12.948902   11.621753           NaN
3                20000  11.725542   12.288707           NaN
4               100000  11.229289   11.920515           NaN
...                ...        ...         ...           ...
4995              5000  12.423452   11.294185           NaN
4996                50  12.781219   12.010374        V-Spec
4997            100000  11.912057   10.319398           NaN
4998              5000  12.473306    9.483797         Turbo
4999             20000  11.267536   10.967698         Sport

[5000 rows x 27 columns]>

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               5000 non-null   str
 1   Model               5000 non-null   str
 2   Year                5000 non-null   int64
 3   Country             5000 non-null   str
 4   Condition           5000 non-null   str
 5   Engine_Size         5000 non-null   float64
 6   Horsepower          5000 non-null   int64
 7   Torque              5000 non-null   int64
 8   Weight              5000 non-null   int64
 9   Top_Speed           5000 non-null   int64
 10  Acceleration_0_100  5000 non-null   float64
 11  Fuel_Type           5000 non-null   str
 12  Drivetrain          5000 non-null   str
 13  Transmission        5000 non-null   str
 14  Fuel_Efficiency     5000 non-null   float64
 15  CO2_Emissions       5000 non-null   int64
 16  Price               5000 non-null   int64
 17  Mileage             5000 non-null   int64
 18  Popularity          5000 non-null   str
 19  Safety_Rating       5000 non-null   int64
 20  Number_of_Owners    5000 non-null   int64
 21  Market_Demand       5000 non-null   str
 22  Insurance_Cost      5000 non-null   int64
 23  Production_Units    5000 non-null   int64
 24  Log_Price           5000 non-null   float64
 25  Log_Mileage         5000 non-null   float64
 26  Modification        1977 non-null   str
dtypes: float64(5), int64(12), str(10)
memory usage: 1.0 MB

In [86]:
df[['Brand','Model']]

          Brand           Model
0        Nissan            720S
1       McLaren     911 Turbo S
2     Chevrolet  M4 Competition
3       Bugatti          Chiron
4        Nissan          Chiron
...         ...             ...
4995     Nissan            GT-R
4996    McLaren  M4 Competition
4997    Bugatti     911 Turbo S
4998    Porsche  M4 Competition
4999    McLaren          Chiron

[5000 rows x 2 columns]

In [87]:
df.isnull().sum()

Brand                    0
Model                    0
Year                     0
Country                  0
Condition                0
Engine_Size              0
Horsepower               0
Torque                   0
Weight                   0
Top_Speed                0
Acceleration_0_100       0
Fuel_Type                0
Drivetrain               0
Transmission             0
Fuel_Efficiency          0
CO2_Emissions            0
Price                    0
Mileage                  0
Popularity               0
Safety_Rating            0
Number_of_Owners         0
Market_Demand            0
Insurance_Cost           0
Production_Units         0
Log_Price                0
Log_Mileage              0
Modification          3023
dtype: int64

In [102]:
df.dropna()

AttributeError: 'list' object has no attribute 'dropna'

In [109]:
print(type(df))

<class 'pandas.DataFrame'>

In [108]:
df.dropna()

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
0,Nissan,720S,2006,Asia,used,3.7,420,705,1785,238,...,96664,Low,2,4,Medium,13410,5000,11.309352,11.479007,V-Spec
6,Porsche,720S,1988,Asia,new,4.2,810,1222,2130,245,...,222953,Medium,4,3,Medium,5645,5000,12.895287,12.314721,Nismo
7,Nissan,720S,2020,USA,new,7.4,1189,184,1526,185,...,202882,High,2,4,Medium,12037,50,11.804131,12.220385,V-Spec
12,Chevrolet,DBS,2008,Europe,new,2.1,871,173,1490,186,...,45449,Low,1,4,Medium,9625,1000,10.655210,10.724368,Supercharged
13,Porsche,Huracan,2014,Europe,used,7.0,721,1364,1095,383,...,115875,Medium,2,1,Low,14327,5000,12.758603,11.660276,GT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,Aston Martin,720S,1985,Asia,new,4.0,953,1067,1050,276,...,177068,High,4,4,Medium,13650,200,12.758813,12.084295,Turbo
4994,BMW,Chiron,2013,Europe,used,7.7,1258,983,1440,309,...,53691,High,3,4,Low,12474,200,11.918771,10.891019,Nismo
4996,McLaren,M4 Competition,2021,USA,new,6.9,256,662,2131,223,...,164451,High,1,3,Low,1134,50,12.781219,12.010374,V-Spec
4998,Porsche,M4 Competition,2023,Asia,new,7.3,1373,228,1161,204,...,13144,Low,4,2,High,11219,5000,12.473306,9.483797,Turbo
4999,McLaren,Chiron,2018,Europe,new,7.7,1075,1037,1312,381,...,57970,High,2,3,High,1802,20000,11.267536,10.967698,Sport

In [113]:
df.columns

Index(['Brand', 'Model', 'Year', 'Country', 'Condition', 'Engine_Size',
       'Horsepower', 'Torque', 'Weight', 'Top_Speed', 'Acceleration_0_100',
       'Fuel_Type', 'Drivetrain', 'Transmission', 'Fuel_Efficiency',
       'CO2_Emissions', 'Price', 'Mileage', 'Popularity', 'Safety_Rating',
       'Number_of_Owners', 'Market_Demand', 'Insurance_Cost',
       'Production_Units', 'Log_Price', 'Log_Mileage', 'Modification'],
      dtype='str')

In [116]:
df['Top_Speed'].min()

np.int64(150)

In [117]:
df["Brand"].value_counts()

Brand
Ferrari         533
Chevrolet       516
Porsche         513
Aston Martin    513
Bugatti         507
BMW             496
McLaren         486
Ford            486
Nissan          480
Lamborghini     470
Name: count, dtype: int64

In [130]:
df[df['Brand']=='BMW'].sort_values(by='Engine_Size')

,Brand,Model,Year,Country,Condition,Engine_Size,Horsepower,Torque,Weight,Top_Speed,...,Mileage,Popularity,Safety_Rating,Number_of_Owners,Market_Demand,Insurance_Cost,Production_Units,Log_Price,Log_Mileage,Modification
3233,BMW,488 GTB,2004,Europe,new,1.6,783,1714,1748,301,...,100220,Low,4,1,Low,9145,100000,13.001106,11.515133,NaN
1186,BMW,Chiron,2008,Asia,used,1.6,919,308,1348,396,...,148016,High,2,3,High,13162,5000,12.908341,11.905082,NaN
4425,BMW,488 GTB,2016,Asia,used,1.6,753,1412,909,218,...,243960,High,2,1,Low,1909,20000,12.119954,12.404764,NaN
4093,BMW,Huracan,2009,Asia,new,1.6,958,674,2268,160,...,80410,Medium,1,3,Medium,3027,20000,11.004962,11.294906,Track Edition
4234,BMW,Corvette Z06,1988,USA,new,1.6,1334,1656,1697,380,...,23120,Low,4,3,Medium,4801,20000,12.209651,10.048497,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1625,BMW,Chiron,2021,USA,new,8.0,591,729,2165,205,...,134896,Medium,1,3,Medium,2925,20000,12.925199,11.812267,NaN
3563,BMW,Huracan,1980,USA,new,8.0,1283,397,1272,307,...,77067,Low,1,2,Medium,9451,100000,11.810442,11.252443,GT
2970,BMW,GT-R,1989,Europe,new,8.0,819,410,2275,248,...,241005,High,4,1,Medium,12350,20000,12.453167,12.392577,NaN
4192,BMW,Mustang GT,1981,Europe,salvage,8.0,216,787,1950,277,...,4959,High,1,3,Low,12834,200,11.537940,8.509161,NaN
4793,BMW,GT-R,1998,Europe,new,8.0,919,776,1510,236,...,149432,Low,2,4,High,14646,100000,11.775090,11.914603,NaN